name: Build Windows App

on:
  workflow_dispatch:   # Allows manual trigger from the GitHub Actions tab

jobs:
  build-windows:
    runs-on: windows-latest
    steps: 
      - name: Checkout Code
        uses: actions/checkout@v5
        with:
          clean: true
          fetch-depth: 0


      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install pnpm
        uses: pnpm/action-setup@v6

      - name: Build React Frontend
        run: |
          pnpm install
          pnpm run build

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.11

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install fastapi uvicorn websockets pydantic pywebview pyinstaller

      - name: Package with PyInstaller
        # This bundles the python env, the Vite /dist folder, and your /public images into a single .exe
        run: |
          pyinstaller --noconfirm --onefile --windowed --name "Splenda" --distpath "out" --add-data "dist;dist" --add-data "public;public" desktop.py

      - name: Upload Windows Executable
        uses: actions/upload-artifact@v6
        with:
          name: Splenda-Windows-App
          path: out/Splenda.exe
